name: umlet-standalone
title: UMLet
version: '14.3.0'
summary: Free UML Tool for Fast UML Diagrams 
description: |
  UMLet is a free, open-source UML tool with a simple user interface: draw UML diagrams fast,
  build sequence and activity diagrams from plain text, export diagrams to eps, pdf, jpg, svg,
  and clipboard, share diagrams using Eclipse, and create new, custom UML elements. 

  This is a community build based on the standalone executable without support by the original 
  authors. 
  
  Official downloads are available here: https:/www.umlet.com 
base: core20  
grade: stable 
confinement: strict
architectures: [amd64]
compression: lzo
license: GPL-3.0-only
environment:
  JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin
  JAVA_CMD: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin/java
  UMLET_JAVA_OPTS: --patch-module java.desktop=$SNAP/Umlet/java-patches/compiled/java.desktop -Duser.home=$SNAP_USER_DATA
  UMLET_HOME: $SNAP/Umlet
  PATH: $SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin:$SNAP/Umlet:$PATH
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib

apps:
  umlet-standalone:
    command: Umlet/umlet.sh
    desktop: usr/share/applications/umlet-standalone.desktop
    extensions: [gnome-3-38]
    plugs:
      - home
      - removable-media
      - optical-drive
      - unity7
      - network 
      - mount-observe
      - process-control
      - network-bind
      - network-observe

parts:
  get-jar:
    plugin: nil 
    build-packages:
      - wget
      - unzip
    override-build: |
      wget https://www.umlet.com/download/umlet_14_3/umlet-standalone-14.3.0.zip      
      unzip -o -d $SNAPCRAFT_PART_INSTALL umlet*.zip 
      
      wget https://github.com/digidigital/UMLet-snap/raw/main/java-patches/compiled/java.desktop/sun/awt/X11/XDesktopPeer.class
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/Umlet/java-patches/compiled/java.desktop/sun/awt/X11
      mv XDesktopPeer.class ${SNAPCRAFT_PART_INSTALL}/Umlet/java-patches/compiled/java.desktop/sun/awt/X11/XDesktopPeer.class
      
      wget https://raw.githubusercontent.com/digidigital/runescape-snap/master/osrs/java-patches/src/java.desktop/unix/classes/sun/awt/X11/DesktopPeer.java
      wget https://raw.githubusercontent.com/digidigital/runescape-snap/master/osrs/java-patches/src/java.desktop/unix/classes/sun/awt/X11/XDesktopPeer.java
      
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/Umlet/java-patches/src/java.desktop/unix/classes/sun/awt/X11
      mv *.java ${SNAPCRAFT_PART_INSTALL}/Umlet/java-patches/src/java.desktop/unix/classes/sun/awt/X11/

      chmod +x $SNAPCRAFT_PART_INSTALL/Umlet/umlet.sh
      mkdir -p ${SNAPCRAFT_PRIME}/usr/share/applications
      cp -r ${SNAPCRAFT_PART_INSTALL}/Umlet/img/umlet_logo.png ${SNAPCRAFT_PRIME}/usr/share/applications/umlet-standalone.png
      
    override-prime: |
      echo '[Desktop Entry]
      Encoding=UTF-8
      Type=Application
      Name=UMLet
      GenericName=UMLet
      Comment=Free UML Tool for Fast UML Diagrams
      Exec=umlet-standalone
      Icon=usr/share/applications/umlet-standalone.png
      Terminal=false
      Categories=Development;
      StartupNotify=true' > ${SNAPCRAFT_PRIME}/usr/share/applications/umlet-standalone.desktop
      
      snapcraftctl prime
      
      rm ${SNAPCRAFT_STAGE}/usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs
      touch ${SNAPCRAFT_STAGE}/usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs

  packages:
    plugin: nil
    stage-packages:  
      - openjdk-11-jre
      - ca-certificates
      - ca-certificates-java
    build-packages:
      - ca-certificates
      - ca-certificates-java
